DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA INT NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);
INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES (32589, 'Julian', 'Garcia');
INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES (32589, 'Pedro', 'Garzon')
